language: node_js
node_js:
  - "8"
cache: npm

matrix:
  fast_finish: true
  include:
    - os: osx
      osx_image: xcode9.1
      env: TEST_COMMAND=test
    - os: linux
      dist: trusty
      env: TEST_COMMAND=test

before_install:
  - |
    if [ "$TRAVIS_OS_NAME" = "osx" ]; then
      curl -LO https://github.com/neovim/neovim/releases/download/nightly/nvim-macos.tar.gz
      tar xzf nvim-macos.tar.gz
      export PATH="${PATH}:node_modules/.bin:$(pwd)/nvim-osx64/bin"
    else
      curl -LO https://github.com/neovim/neovim/releases/download/nightly/nvim-linux64.tar.gz
      tar xzf nvim-linux64.tar.gz
      export PATH="${PATH}:node_modules/.bin:$(pwd)/nvim-linux64/bin"
    fi
  - echo $PATH
  - nvim --version

install:
  - npm install

script:
  - export NODE_ENV=test
  - npm run $TEST_COMMAND

notifications:
  email:
    on_success: never
    on_failure: never
    on_cancel: never
    on_error: never
